/**
 * @file main_func.h
 * @brief Main functions for the application.
 * 
 * This file contains the function declarations for the main
 * functions of the application.
 * It includes signal handlers, server and client mode functions.
 */

#ifndef MAIN_FUNC_H
#define MAIN_FUNC_H

#include <stdbool.h> 

/**
 * @brief Signal handler for SIGINT.
 * 
 * This function handles the SIGINT signal (usually generated by pressing Ctrl+C).
 * It closes the server socket if it is open and exits the program.
 * 
 * @param sig The signal number.
 */
void handle_sigint (int sig);

/**
 * @brief Exit handler.
 * 
 * This function is called when the program exits. It calls the handle_sigint function
 * to ensure that resources are cleaned up properly.
 */
void handle_exit ();

/**
 * @brief Setup signal handlers.
 * 
 * This function sets up the signal handlers for the program. It handles SIGINT and
 * ensures that the handle_exit function is called when the program exits.
 */
void setup_signal_handlers ();

/**
 * @brief Start the server mode.
 * 
 * This function starts the server mode. It initializes the server socket, accepts a client connection,
 * and starts the terminal network for the server.
 * 
 * @param port The port number to start the server on.
 */
void start_server_mode (short port,bool ai);

/**
 * @brief Start the client mode.
 * 
 * This function starts the client mode. It connects to the server using the provided IP address and port,
 * and starts the terminal network for the client.
 * 
 * @param ip The IP address of the server.
 * @param port The port number of the server.
 */
void start_client_mode (const char *ip, short port,bool ai);



#endif // MAIN_FUNC_H