/**
 * @file main_func.c
 * @brief Main functions for the application.
 * 
 * This file contains the main functions for the application.
 * It includes signal handlers, server and client mode functions, and the main function.
 */

#include "main_func.h"
#include <stdbool.h>
#include <signal.h>
#include "gui.h"
#include "network.h"
#include "const.h"
#include "terminal.h"

/**
 * @brief Signal handler for SIGINT.
 * 
 * This function handles the SIGINT signal (usually generated by pressing Ctrl+C).
 * It closes the server socket if it is open and exits the program.
 * 
 * @param sig The signal number.
 */
void
handle_sigint (int sig)
{
    (void) sig; // Suppress unused parameter warning
    if (server_socket != -1) {
        close (server_socket);
        server_socket = -1; // Mark the socket as closed
        printf ("\nServer socket closed.\n");
    }
    exit (0);
}

/**
 * @brief Exit handler.
 * 
 * This function is called when the program exits. It calls the handle_sigint function
 * to ensure that resources are cleaned up properly.
 */
void handle_exit ()
{
       if (client_socket != -1) {
           close(client_socket);
           client_socket = -1;
           printf("Client socket closed.\n");
       }
       if (server_socket != -1) {
           close(server_socket);
           server_socket = -1;
           printf("Server socket closed.\n");
       }
       exit(0);
   }

/**
 * @brief Setup signal handlers.
 * 
 * This function sets up the signal handlers for the program. It handles SIGINT and
 * ensures that the handle_exit function is called when the program exits.
 */
void
setup_signal_handlers ()
{
    signal (SIGINT, handle_sigint); // Set up SIGINT handler
    atexit (handle_exit); // Register exit handler
}

/**
 * @brief Start the server mode.
 * 
 * This function starts the server mode. It initializes the server socket, accepts a client connection,
 * and starts the terminal network for the server.
 * 
 * @param port The port number to start the server on.
 * @param ai If we want to run it with ai or not
 */
void
start_server_mode (short port,bool ai)
{
    server_socket = start_server (port); // Initialize server socket
    client_socket = accept (server_socket, NULL, NULL); // Accept client connection
    player = 2; // Set player to server
    if (!ai){
        start_terminal_network (client_socket, player); // Start terminal network for server
    }else{
        start_terminal_network_ai(client_socket,player);
    }
    close (client_socket); // Close client socket
    close (server_socket); // Close server socket
}

/**
 * @brief Start the client mode.
 * 
 * This function starts the client mode. It connects to the server using the provided IP address and port,
 * and starts the terminal network for the client.
 * 
 * @param ip The IP address of the server.
 * @param port The port number of the server.
 * @param ai If we want to run it with ai or not
 */
void
start_client_mode (const char *ip, short port,bool ai)
{
    client_socket = start_client (ip, port); // Connect to server
    player = 1; // Set player to client
    if (!ai){
        start_terminal_network (client_socket, player); // Start terminal network for client
    }else{
        start_terminal_network_ai (client_socket, player); // Start terminal network for client
    }
    close (client_socket); // Close client socket
}
